name: Run Python Script

on:
  schedule:
    - cron: '0 */23 * * *'  # تشغيل السكربت كل 6 ساعات

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # تحديد إصدار Python

    - name: Install dependencies
      run: |
        pip install -r a.txt

    - name: Run Python script
      run: |
        python bot
